// This file is generated by rust-protobuf 2.27.1. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `common.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_27_1;

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
pub enum ChipKind {
    UNSPECIFIED = 0,
    BLUETOOTH = 1,
    WIFI = 2,
    UWB = 3,
}

impl ::protobuf::ProtobufEnum for ChipKind {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<ChipKind> {
        match value {
            0 => ::std::option::Option::Some(ChipKind::UNSPECIFIED),
            1 => ::std::option::Option::Some(ChipKind::BLUETOOTH),
            2 => ::std::option::Option::Some(ChipKind::WIFI),
            3 => ::std::option::Option::Some(ChipKind::UWB),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [ChipKind] = &[
            ChipKind::UNSPECIFIED,
            ChipKind::BLUETOOTH,
            ChipKind::WIFI,
            ChipKind::UWB,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            ::protobuf::reflect::EnumDescriptor::new_pb_name::<ChipKind>("ChipKind", file_descriptor_proto())
        })
    }
}

impl ::std::marker::Copy for ChipKind {
}

impl ::std::default::Default for ChipKind {
    fn default() -> Self {
        ChipKind::UNSPECIFIED
    }
}

impl ::protobuf::reflect::ProtobufValue for ChipKind {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Enum(::protobuf::ProtobufEnum::descriptor(self))
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0ccommon.proto\x12\rnetsim.common*=\n\x08ChipKind\x12\x0f\n\x0bUNSPE\
    CIFIED\x10\0\x12\r\n\tBLUETOOTH\x10\x01\x12\x08\n\x04WIFI\x10\x02\x12\
    \x07\n\x03UWB\x10\x03b\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
